"""Aggiunto hostname alla tabella delle credenziali

Revision ID: 0206f17e74a4
Revises: 3a61fb1b8d43
Create Date: 2025-12-21 14:25:41.127821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0206f17e74a4'
down_revision = '3a61fb1b8d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostname', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_credentials', schema=None) as batch_op:
        batch_op.drop_column('hostname')

    # ### end Alembic commands ###
