"""Aggiunta tabella credenziali

Revision ID: 3a61fb1b8d43
Revises: 8cc9a31090bf
Create Date: 2025-12-20 12:41:02.140518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a61fb1b8d43'
down_revision = '8cc9a31090bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_request_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('add_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vm_request_id'], ['vm_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm_credentials')
    # ### end Alembic commands ###
